import { ArrowDown, ArrowRight, CircleCheck, Database, FileCheck2, RefreshCw, Server, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { motion, useReducedMotion } from "framer-motion";
import SEO from "@/components/common/SEO";
import { HeroDashboard, InvoiceMockup, MobileMockup, NetworkDiagram, POSBillingDemo, ReportsDashboard } from "@/components/dashboard/DashboardMockups";
import ProductGallery from "@/components/sections/ProductGallery";
import { Badge, Button, Container, Reveal, SectionHeading } from "@/components/ui";
import { features, industries, products, workflow } from "@/data/siteData";
import { siteConfig } from "@/config/siteConfig";

const homeFaqs = [
  ["What is TurboCart?", "TurboCart is retail ERP and POS software that connects billing, inventory, purchases, suppliers, customers, pricing and reports across Windows, Cloud and Mobile experiences."],
  ["What is the difference between Elite, Pro and Platinum?", "Elite is the standalone Windows edition. Pro is the Windows server and client edition for multiple connected billing systems. Platinum is the multi-branch cloud SaaS with cross-platform access, dedicated backups and your own mobile e-commerce app."],
  ["Can TurboCart run on multiple billing counters?", "Yes. TurboCart Pro uses a Windows server and client deployment so multiple billing systems can connect through the local area network."],
  ["Can billing continue without an internet connection?", "TurboCart Windows is designed for dependable local operation. Cloud and mobile experiences require the connectivity appropriate to their remote-access features."],
  ["Which businesses can use TurboCart?", "TurboCart can support supermarkets, grocery stores, electrical and electronics shops, computer and IT stores, automobile-parts inventory, department stores, wholesalers and other billing-based businesses."],
  ["Does TurboCart manage stock and purchases as well as billing?", "Yes. The platform connects POS billing with products, inventory, purchase entry, suppliers, pricing, customers and operational reports."],
  ["Can TurboCart be customized for my business?", "Yes. If your workflow needs fields, reports, billing steps or features beyond the standard product, contact the TurboCart team to discuss a customization designed around your requirements."],
  ["How can I evaluate TurboCart for my store?", "Request a guided demo and share your store count, billing-counter count and preferred product. The team can then focus the walkthrough on your retail workflow."],
] as const;

const homeSchema = [
  {
    "@type": "WebSite",
    "@id": `${siteConfig.url}/#website`,
    url: siteConfig.url,
    name: "TurboCart",
    alternateName: "TurboCart Retail ERP & POS",
    inLanguage: "en-IN",
    publisher: { "@id": `${siteConfig.url}/#organization` },
  },
  {
    "@type": "Organization",
    "@id": `${siteConfig.url}/#organization`,
    name: "Sysygo Innovations",
    url: siteConfig.url,
    logo: `${siteConfig.url}/images/brand/turbocart-logo.png`,
    brand: { "@type": "Brand", name: "TurboCart" },
    contactPoint: { "@type": "ContactPoint", telephone: "+91-80758-15183", contactType: "technical support", email: "support@sysgo.in", availableLanguage: ["English", "Malayalam"] },
  },
  {
    "@type": "SoftwareApplication",
    "@id": `${siteConfig.url}/#software`,
    name: "TurboCart",
    url: siteConfig.url,
    description: "Customizable ERP, inventory and POS software for billing, purchases, suppliers, customers and reporting across many business types.",
    applicationCategory: "BusinessApplication",
    operatingSystem: "Windows, Android, Linux, macOS, Web",
    image: `${siteConfig.url}/images/brand/turbocart-og.jpg`,
    publisher: { "@id": `${siteConfig.url}/#organization` },
    featureList: ["Elite standalone Windows billing", "Pro Windows server and client deployment", "Platinum multi-branch cloud SaaS", "99.99% cloud uptime", "Dedicated cloud backups", "Cross-platform browser access", "Own mobile e-commerce app", "Requirement-based feature development"],
  },
  {
    "@type": "FAQPage",
    mainEntity: homeFaqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })),
  },
];

function Hero() {
  const reduced = useReducedMotion();
  return <section className="relative overflow-hidden pb-24 pt-32 sm:pt-40 lg:pb-32"><div className="site-grid absolute inset-0"/><div className="noise pointer-events-none absolute inset-0 opacity-[.025]"/><motion.div animate={reduced?{}:{x:[0,80,0],y:[0,30,0]}} transition={{duration:15,repeat:Infinity}} className="absolute left-[20%] top-16 h-[420px] w-[420px] rounded-full bg-blue-600/20 blur-[130px]"/><div className="absolute right-[5%] top-52 h-[340px] w-[340px] rounded-full bg-cyan-400/10 blur-[120px]"/>
  <Container className="relative"><div className="mx-auto max-w-5xl text-center"><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}}><Badge><span className="h-1.5 w-1.5 rounded-full bg-cyan-300"/> One adaptable business ecosystem</Badge></motion.div><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}} transition={{delay:.1,duration:.7}} className="mt-7 text-balance text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-7xl lg:text-[88px]">Your business is unique.<br/><span className="text-gradient">Your software can be too.</span></motion.h1><motion.p initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.2,duration:.7}} className="mx-auto mt-7 max-w-3xl text-base leading-8 text-slate-400 sm:text-xl">Customizable billing, inventory, purchasing and business management for grocery, electrical, electronics, IT, automobile and other businesses.</motion.p><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{delay:.3}} className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button to="/request-demo" className="sm:min-w-44">Discuss your requirements</Button><Button to={siteConfig.loginUrl} variant="secondary" className="sm:min-w-44">Explore TurboCart</Button></motion.div><p className="mt-5 text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Use the standard product or customize it around your workflow</p></div><div className="mt-16 lg:mt-20"><HeroDashboard/></div></Container></section>;
}

function Ecosystem() { return <section id="ecosystem" className="py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="One connected platform" title="Every side of retail. One ecosystem." description="Choose the experience that fits your operation—from local checkout performance to remote business visibility."/></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{products.map(({name,path,icon:Icon,eyebrow,title,description,accent},i)=><Reveal key={path} delay={i*.08}><Link to={path} className={`card-hover group flex min-h-[340px] flex-col rounded-3xl border border-white/10 bg-gradient-to-br ${accent} p-7 sm:p-8`}><div className="flex items-center justify-between"><span className="rounded-2xl border border-white/10 bg-black/20 p-3 text-cyan-200"><Icon className="h-6 w-6"/></span><span className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">{eyebrow}</span></div><h3 className="mt-16 text-2xl font-extrabold tracking-tight">{name}</h3><p className="mt-3 text-lg font-bold text-slate-200">{title}</p><p className="mt-3 leading-7 text-slate-400">{description}</p><span className="mt-auto flex items-center gap-2 pt-8 text-sm font-bold text-cyan-300">Explore product <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1"/></span></Link></Reveal>)}</div></Container></section>; }

function RealProduct() { return <section className="border-y border-white/[.07] bg-night py-24 lg:py-32"><Container><Reveal><SectionHeading eyebrow="Inside TurboCart" title="Real software. Built for the retail floor." description="Explore the actual TurboCart Windows interface across billing, purchasing, finance, reporting and day-to-day store operations."/></Reveal><Reveal className="mt-12"><ProductGallery compact/></Reveal></Container></section>; }

function Workflow() { return <section className="border-y border-white/[.07] bg-night py-24 lg:py-32"><Container><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><Reveal><SectionHeading eyebrow="Retail workflow" title={<>From purchase to checkout.<br/><span className="text-slate-500">TurboCart connects everything.</span></>} description="Information moves through your operation as one connected retail workflow—not a collection of disconnected tasks."/><Button to="/solutions" variant="secondary" className="mt-8">Explore solutions</Button></Reveal><Reveal className="grid grid-cols-2 gap-3 sm:grid-cols-4">{workflow.map((item,i)=><div key={item} className="relative rounded-2xl border border-white/10 bg-white/[.035] p-4 sm:p-5"><span className="text-[10px] font-extrabold text-cyan-300">0{i+1}</span><p className="mt-5 text-sm font-bold">{item}</p>{i<workflow.length-1&&<ArrowDown className="absolute -bottom-5 left-1/2 z-10 h-5 w-5 -translate-x-1/2 text-blue-400 sm:hidden"/>}</div>)}</Reveal></div></Container></section>; }

function Billing() { return <section className="py-24 lg:py-32"><Container><Reveal><SectionHeading eyebrow="At the counter" title="Built for the speed of checkout." description="When queues grow, every second matters. TurboCart provides a streamlined POS workflow designed for fast and dependable retail billing."/></Reveal><Reveal className="mt-12"><POSBillingDemo/></Reveal></Container></section>; }

function Operations() { const ops = [["Inventory clarity","Know what you have before you run out.","Track product quantities, stock movement, categories and reorder attention from one organized view.",["Total products","Low-stock attention","Recent movement"]],["Connected purchasing","Purchasing without spreadsheet chaos.","Bring suppliers, purchase records, goods received, cost details and payment tracking into a single flow.",["Supplier information","Stock intake","Payment tracking"]]] as const; return <section className="bg-night py-24 lg:py-32"><Container><div className="grid gap-5 lg:grid-cols-2">{ops.map((o,i)=><Reveal key={o[0]} delay={i*.08} className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/[.045] to-transparent p-7 sm:p-10"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">{o[0]}</p><h3 className="mt-5 text-3xl font-extrabold tracking-tight">{o[1]}</h3><p className="mt-4 leading-7 text-slate-400">{o[2]}</p><div className="mt-9 space-y-3">{o[3].map(x=><div className="flex items-center gap-3 rounded-xl border border-white/[.07] bg-black/10 p-3 text-sm text-slate-300" key={x}><CircleCheck className="h-4 w-4 text-cyan-300"/>{x}</div>)}</div></Reveal>)}</div></Container></section>; }

function Invoice() { return <section className="overflow-hidden py-24 lg:py-32"><Container><div className="grid items-center gap-16 lg:grid-cols-2"><Reveal><SectionHeading eyebrow="GST & invoices" title="Professional billing built for Indian retail." description="Organize tax information, sales records, purchase records, invoice history and A4 printing through a clear billing workflow."/><div className="mt-8 flex flex-wrap gap-2">{["GST-ready invoices","A4 printing","Invoice history","Sales records"].map(x=><span key={x} className="rounded-full border border-white/10 bg-white/[.035] px-4 py-2 text-xs text-slate-300">{x}</span>)}</div><p className="mt-5 text-xs text-slate-600">No government certification is implied.</p></Reveal><Reveal><InvoiceMockup/></Reveal></div></Container></section>; }

function Reports() { return <section className="bg-night py-24 lg:py-32"><Container><div className="grid gap-12 lg:grid-cols-[.65fr_1.35fr] lg:items-center"><Reveal><SectionHeading eyebrow="Reports & insights" title="Turn every transaction into insight." description="Review sales trends, purchases, stock summaries, top products and daily closing information through clear retail reporting."/><p className="mt-5 text-xs text-slate-600">All values shown are demonstration data.</p><Button to="/features" variant="secondary" className="mt-8">Explore reporting</Button></Reveal><Reveal><ReportsDashboard/></Reveal></div></Container></section>; }

function CloudMobile() { return <section className="border-y border-white/[.07] bg-night py-24 lg:py-32"><Container><div className="grid gap-16 lg:grid-cols-2 lg:items-center"><Reveal><SectionHeading eyebrow="TurboCart Platinum" title={<>Every branch.<br/><span className="text-gradient">One cloud SaaS.</span></>} description="Run centralized multi-branch operations with 99.99% uptime, dedicated backups and browser access across Android, Windows, Linux and macOS."/><div className="mt-12"><NetworkDiagram/></div></Reveal><Reveal><SectionHeading eyebrow="Your own e-commerce app" title="Take your business to your customers." description="Platinum includes a customer-facing mobile e-commerce application connected with your cloud product, inventory and order ecosystem."/><div className="mt-10"><MobileMockup/></div></Reveal></div></Container></section>; }

function Infrastructure() { return <section className="py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="TurboCart Pro" title="Local performance across every counter." description="The Pro edition connects a Windows server and multiple client billing systems through the local network. Choose Elite when one standalone Windows system is enough."/></Reveal><div className="mx-auto mt-14 max-w-4xl"><Reveal><div className="flex flex-col items-center"><div className="rounded-2xl border border-blue-400/30 bg-blue-500/10 p-5 text-center"><Server className="mx-auto h-7 w-7 text-cyan-300"/><p className="mt-2 font-bold">Pro main server</p><p className="text-xs text-slate-500">Local Windows database operation</p></div><div className="h-12 w-px bg-cyan-300/50"/><div className="grid w-full grid-cols-2 gap-3 sm:grid-cols-4">{[1,2,3,4].map(n=><div key={n} className="relative rounded-xl border border-white/10 bg-white/[.035] p-4 text-center"><i className="absolute left-1/2 top-[-49px] h-12 w-px bg-blue-500/40"/><p className="text-sm font-bold">Pro client {n}</p><p className="mt-1 flex items-center justify-center gap-1 text-[10px] text-emerald-300"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-300"/>Connected</p></div>)}</div></div></Reveal></div>
  <div className="mt-20 grid gap-5 lg:grid-cols-2"><Reveal className="rounded-3xl border border-white/10 bg-gradient-to-br from-blue-500/10 to-transparent p-8"><ShieldCheck className="h-8 w-8 text-cyan-300"/><h3 className="mt-6 text-2xl font-extrabold">Your business data deserves protection.</h3><p className="mt-4 leading-7 text-slate-400">Structured backup and restoration workflows are designed to protect important business data.</p><div className="mt-7 flex items-center gap-3 text-xs font-bold text-slate-300"><Database/> <ArrowRight/> <FileCheck2/> <ArrowRight/> <ShieldCheck/></div></Reveal><Reveal delay={.08} className="rounded-3xl border border-white/10 bg-gradient-to-br from-violet-500/10 to-transparent p-8"><RefreshCw className="h-8 w-8 text-violet-300"/><h3 className="mt-6 text-2xl font-extrabold">Update software. Keep your business data.</h3><p className="mt-4 leading-7 text-slate-400">TurboCart’s normal update workflow is designed to preserve the business information already in your system.</p></Reveal></div></Container></section>; }

function Features() { return <section className="bg-night py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="Complete retail control" title="The tools behind everyday retail." description="From the first purchase entry to daily closing, TurboCart brings core operations into one consistent platform."/></Reveal><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,title,desc],i)=><Reveal key={title} delay={(i%4)*.04} className={`card-hover rounded-2xl border border-white/10 bg-white/[.025] p-6 ${i===0||i===8?"lg:col-span-2":""}`}><Icon className="h-6 w-6 text-cyan-300"/><h3 className="mt-7 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></Reveal>)}</div><div className="mt-10 text-center"><Button to="/features" variant="secondary">View all features</Button></div></Container></section>; }

function Industries() { return <section className="py-24 lg:py-32"><Container><Reveal><SectionHeading eyebrow="Built for different businesses" title="Ready for the way your business operates." description="TurboCart can replace basic billing software with connected billing, inventory and business management for many product-based industries."/></Reveal><div className="mt-12 grid grid-cols-2 gap-3 lg:grid-cols-3">{industries.map(([Icon,name])=><Reveal key={name} className="card-hover rounded-2xl border border-white/10 bg-white/[.025] p-5 sm:p-7"><Icon className="h-6 w-6 text-cyan-300"/><p className="mt-6 text-sm font-bold sm:text-base">{name}</p></Reveal>)}</div><div className="mt-10"><Button to="/industries" variant="secondary">Explore supported businesses</Button></div></Container></section>; }

function WhyTurboCart() { const reasons=[["Fast billing","Designed for busy checkout environments."],["Complete retail control","Bring sales, inventory, purchases and customers together."],["Windows + Cloud + Mobile","Choose the experience that fits your operation."],["Multi-terminal ready","Connect billing counters through the local network."],["Data protection","Structured backup and restoration workflows."],["Ready to grow","Move from focused billing to wider retail management."]]; return <section className="border-y border-white/[.07] bg-night py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="Why TurboCart" title="Built around how retail actually works."/></Reveal><div className="mt-12 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-2 lg:grid-cols-3">{reasons.map(([title,desc],i)=><Reveal key={title} delay={(i%3)*.04} className="bg-night p-7 sm:p-8"><span className="text-xs font-extrabold text-cyan-300">0{i+1}</span><h3 className="mt-6 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{desc}</p></Reveal>)}</div></Container></section>; }

function ProductComparison() { const rows=[["Best for","One Windows billing system","Multiple LAN billing systems","Multi-branch cloud operations"],["Deployment","Standalone Windows","Windows server + clients","Cloud SaaS"],["Billing & inventory","Included","Included","Centralized across branches"],["Multi-counter operation","Single system","Server + client setup","Branch and cloud access"],["Supported access","Windows","Windows","Android, Windows, Linux, macOS"],["Dedicated backup facility","Local backup workflow","Local backup workflow","Included"],["Own mobile e-commerce app","Not included","Not included","Included"],["Cloud uptime","Not applicable","Not applicable","99.99%*"],["Customization","Available","Available","Available"]]; return <section className="py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="Choose your TurboCart edition" title="Elite. Pro. Platinum." description="Select standalone Windows billing, a connected Windows server and client deployment, or complete multi-branch cloud SaaS with mobile commerce."/></Reveal><Reveal className="mt-12 overflow-x-auto rounded-3xl border border-white/10"><table className="w-full min-w-[820px] border-collapse text-left text-sm"><thead className="bg-white/[.045]"><tr><th scope="col" className="p-5 text-slate-500">Capability</th><th scope="col" className="p-5 text-white">Elite</th><th scope="col" className="p-5 text-white">Pro</th><th scope="col" className="p-5 text-white">Platinum</th></tr></thead><tbody>{rows.map((row,i)=><tr key={row[0]} className={i%2?"bg-white/[.018]":""}>{row.map((cell,j)=><td key={cell} className={`border-t border-white/[.07] p-5 ${j===0?"font-bold text-slate-200":"text-slate-400"}`}>{cell}</td>)}</tr>)}</tbody></table></Reveal><p className="mt-4 text-center text-xs text-slate-500">*Subject to applicable TurboCart Cloud service terms and exclusions.</p></Container></section>; }

function RetailSoftwareGuide() { const topics=[["Elite standalone billing","Run dependable billing, inventory, purchases and reports locally on one Windows system."],["Pro server + client","Coordinate a Windows server and connected client billing systems through the local network."],["Platinum multi-branch SaaS","Centralize branch operations in the cloud with cross-platform access, dedicated backups and mobile e-commerce."]]; return <section className="border-y border-white/[.07] bg-night py-24 lg:py-32"><Container><Reveal><SectionHeading eyebrow="Three editions, one adaptable platform" title="Move from one counter to every branch." description="TurboCart provides a clear upgrade path from standalone Windows billing to multi-counter local operation and complete multi-branch cloud SaaS."/></Reveal><div className="mt-12 grid gap-4 lg:grid-cols-3">{topics.map(([title,description],i)=><Reveal key={title} delay={i*.06} className="rounded-2xl border border-white/10 bg-white/[.025] p-7"><span className="text-xs font-extrabold text-cyan-300">0{i+1}</span><h2 className="mt-6 text-xl font-extrabold">{title}</h2><p className="mt-4 leading-7 text-slate-400">{description}</p></Reveal>)}</div><Reveal className="mt-10 max-w-4xl text-base leading-8 text-slate-400"><p>Choose Elite when your business needs a complete standalone Windows billing system. Choose Pro when multiple Windows billing counters need to share a local server and operational database. Choose Platinum when you want centralized SaaS across multiple branches, access from Android, Windows, Linux and macOS, dedicated backups and your own mobile e-commerce application.</p></Reveal></Container></section>; }

function Customization() { const options=[["Your billing workflow","Adapt screens, fields and steps to match how your team creates bills and serves customers."],["Your inventory model","Discuss industry-specific product details, categorization, stock handling and information your business needs to track."],["Your reports and features","Request new reports, operational views or features when the standard product does not fully cover your process."]]; return <section className="py-24 lg:py-32"><Container><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><Reveal><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300">Software that fits</p><h2 className="mt-5 text-4xl font-extrabold tracking-[-.045em] sm:text-5xl">Move beyond one-size-fits-all billing software.</h2><p className="mt-6 text-lg leading-8 text-slate-400">Start with TurboCart’s connected billing and inventory platform, then discuss the changes your business needs. Whether you sell groceries, electrical goods, electronics, computers, automobile parts or another product category, the workflow can be evaluated around your operation.</p><Button to="/contact" className="mt-8">Tell us what you need</Button></Reveal><div className="space-y-4">{options.map(([title,description],i)=><Reveal key={title} delay={i*.06} className="rounded-2xl border border-white/10 bg-gradient-to-r from-blue-500/[.08] to-transparent p-7"><span className="text-xs font-extrabold text-cyan-300">0{i+1}</span><h3 className="mt-4 text-xl font-extrabold">{title}</h3><p className="mt-3 leading-7 text-slate-400">{description}</p></Reveal>)}</div></div></Container></section>; }

function HomeFAQ() { return <section className="py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="TurboCart questions" title="Answers for retail owners and operators." description="Understand how TurboCart fits billing counters, stock management and connected retail operations before requesting a demo."/></Reveal><div className="mx-auto mt-12 max-w-4xl space-y-3">{homeFaqs.map(([question,answer])=><Reveal key={question}><details className="group rounded-2xl border border-white/10 bg-white/[.025] p-5 sm:p-6"><summary className="cursor-pointer list-none pr-8 font-bold text-white">{question}</summary><p className="mt-4 border-t border-white/[.07] pt-4 text-sm leading-7 text-slate-400">{answer}</p></details></Reveal>)}</div></Container></section>; }

function CTA() { return <section className="pb-24 lg:pb-32"><Container><Reveal className="relative overflow-hidden rounded-[32px] border border-blue-400/20 bg-gradient-to-br from-blue-600/25 via-surface to-cyan-400/10 px-6 py-16 text-center sm:px-12 lg:py-24"><div className="absolute left-1/2 top-0 h-40 w-80 -translate-x-1/2 rounded-full bg-cyan-300/20 blur-[80px]"/><div className="relative"><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300">See the platform</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-extrabold tracking-[-.05em] sm:text-6xl">See TurboCart in action.</h2><p className="mx-auto mt-5 max-w-2xl leading-7 text-slate-400">Discover how TurboCart can simplify billing, inventory, purchases and everyday retail management.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Button to="/request-demo">Request a demo</Button><Button to="/contact" variant="secondary">Talk to sales</Button></div></div></Reveal></Container></section>; }

export default function Home() { return <><SEO title="Customizable Billing, Inventory & POS Software | TurboCart" description="TurboCart is customizable billing, inventory and ERP software for grocery, electrical, electronics, IT, automobile and other businesses." schema={homeSchema}/><Hero/><Ecosystem/><RealProduct/><Workflow/><Billing/><Operations/><Invoice/><Reports/><CloudMobile/><Infrastructure/><Features/><Industries/><Customization/><WhyTurboCart/><ProductComparison/><RetailSoftwareGuide/><HomeFAQ/><CTA/></>; }
