import { ArchiveRestore, Boxes, Cloud, Monitor, ReceiptText, Server, ShieldCheck, Smartphone, Store, Wifi } from "lucide-react";
import SEO from "@/components/common/SEO";
import { HeroDashboard, MobileMockup, NetworkDiagram, POSBillingDemo } from "@/components/dashboard/DashboardMockups";
import { Button, Container, PageHero, Reveal, SectionHeading } from "@/components/ui";
import ProductGallery from "@/components/sections/ProductGallery";

const detailCards = {
  windows: [[ReceiptText,"Fast POS billing","A focused checkout workflow designed for busy billing counters."],[Monitor,"Elite edition","A complete standalone Windows billing and inventory setup for a single system."],[Server,"Pro edition","A Windows server and client deployment for businesses operating multiple connected billing systems."],[Wifi,"LAN-based terminals","Connect Pro edition billing computers through the business’s local network."],[ArchiveRestore,"Backup & restore","Use structured workflows for fresh setup or restoring an existing database."],[ShieldCheck,"Safe updates","Update the software while preserving existing business information."]],
  cloud: [[ShieldCheck,"99.99% uptime","Dependable SaaS availability for connected business operations, subject to the applicable service terms."],[Store,"Multi-branch SaaS","Manage multiple business branches through one centralized cloud software account."],[Cloud,"Cross-platform access","Use TurboCart Cloud on Android, Windows, Linux and macOS through a compatible modern browser."],[ArchiveRestore,"Dedicated backups","Protect cloud business information with a dedicated backup facility."],[Boxes,"Central inventory","Organize products and inventory across connected branch operations."],[Smartphone,"Own e-commerce app","Platinum includes a customer-facing mobile e-commerce app for your business."]],
  mobile: [[Smartphone,"Your own e-commerce app","Platinum provides a mobile e-commerce app for your business and customers."],[Store,"Connected product catalogue","Present business products through a mobile shopping experience connected with the cloud ecosystem."],[Boxes,"Cloud-connected inventory","Connect customer-facing commerce with centralized product and inventory information."],[ReceiptText,"Order workflow","Bring mobile customer orders into the connected business workflow."],[Cloud,"Part of Platinum","The mobile e-commerce application is provided with the TurboCart Platinum cloud offering."],[ShieldCheck,"Managed access","Support a controlled, branded digital channel backed by the cloud platform."]],
} as const;

function DetailGrid({ type }: { type: keyof typeof detailCards }) { return <section className="bg-night py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="Core capabilities" title="Designed around real retail operations."/></Reveal><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{detailCards[type].map(([Icon,title,desc],i)=><Reveal key={title} delay={(i%3)*.06} className="card-hover rounded-2xl border border-white/10 bg-white/[.025] p-7"><Icon className="h-6 w-6 text-cyan-300"/><h3 className="mt-8 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{desc}</p></Reveal>)}</div></Container></section>; }

function ProductCTA({ product }: { product: string }) { return <section className="pb-24 pt-8 lg:pb-32"><Container><Reveal className="rounded-3xl border border-blue-400/20 bg-gradient-to-br from-blue-600/20 to-cyan-400/[.06] p-8 text-center sm:p-14"><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">See {product} in action</p><h2 className="mt-5 text-3xl font-extrabold tracking-tight sm:text-5xl">Let’s make your retail workflow clearer.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-slate-400">Request a focused walkthrough based on your stores, counters and day-to-day operating requirements.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Button to="/request-demo">Request a demo</Button><Button to="/contact" variant="secondary">Talk to sales</Button></div></Reveal></Container></section>; }

function WindowsEditions() { const editions=[{name:"Elite",label:"Standalone Windows",description:"A focused Windows edition for a business operating TurboCart on one billing system.",items:["Windows billing and inventory","Local business operation","Structured backup and restore","Ideal for a standalone counter"]},{name:"Pro",label:"Server + client",description:"A connected Windows deployment with a main server and client billing systems over the local network.",items:["Central Windows server","Multiple client billing systems","LAN-based counter connectivity","Shared operational database"]}]; return <section className="py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="Windows editions" title="Choose Elite or Pro." description="Start with a standalone Windows billing system or connect multiple billing counters through a server and client deployment."/></Reveal><div className="mx-auto mt-12 grid max-w-5xl gap-5 md:grid-cols-2">{editions.map((edition,i)=><Reveal key={edition.name} delay={i*.08} className={`rounded-3xl border p-8 sm:p-10 ${i===1?"border-cyan-300/25 bg-gradient-to-br from-blue-500/15 to-cyan-300/[.04]":"border-white/10 bg-white/[.025]"}`}><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">{edition.label}</p><h2 className="mt-4 text-4xl font-extrabold">TurboCart {edition.name}</h2><p className="mt-4 leading-7 text-slate-400">{edition.description}</p><ul className="mt-7 space-y-3">{edition.items.map(item=><li key={item} className="flex items-center gap-3 text-sm text-slate-300"><ShieldCheck className="h-4 w-4 shrink-0 text-cyan-300"/>{item}</li>)}</ul></Reveal>)}</div></Container></section>; }

function PlatinumOverview() { const facts=[["99.99%","Cloud uptime"],["4 platforms","Android · Windows · Linux · macOS"],["One SaaS","Multi-branch management"],["Included","Own mobile e-commerce app"]]; return <section className="py-24 lg:py-32"><Container><Reveal><SectionHeading eyebrow="TurboCart Platinum" title="Cloud software for every branch—and every platform." description="Platinum combines centralized multi-branch SaaS, cross-platform browser access, dedicated backups and your own mobile e-commerce application."/></Reveal><div className="mt-12 grid grid-cols-2 gap-3 lg:grid-cols-4">{facts.map(([value,label],i)=><Reveal key={label} delay={i*.05} className="rounded-2xl border border-white/10 bg-white/[.03] p-6"><p className="text-2xl font-extrabold text-white sm:text-3xl">{value}</p><p className="mt-2 text-sm leading-6 text-slate-400">{label}</p></Reveal>)}</div><p className="mt-5 text-xs text-slate-500">Uptime is measured under the applicable TurboCart Cloud service terms and exclusions.</p></Container></section>; }

function WindowsFAQ() { const items=[["What is the difference between TurboCart Elite and Pro?","Elite is the standalone Windows edition for one billing system. Pro uses a Windows server and client setup to connect multiple billing systems through the local network."],["Can an existing database be restored?","The installation workflow supports a fresh installation or restoration from an existing TurboCart backup."],["Do updates preserve business information?","The normal update workflow is designed to preserve existing business data during software updates."],["Is internet access required for local billing?","Elite and Pro are designed for dependable local Windows operation. Exact deployment and connectivity requirements can be confirmed during setup."]]; return <section className="py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="Frequently asked questions" title="Elite and Pro, clearly explained."/></Reveal><div className="mx-auto mt-12 max-w-3xl space-y-3">{items.map(([question,answer])=><details key={question} className="group rounded-2xl border border-white/10 bg-white/[.025] p-5"><summary className="cursor-pointer list-none pr-8 font-bold text-white">{question}</summary><p className="mt-4 border-t border-white/[.07] pt-4 text-sm leading-7 text-slate-400">{answer}</p></details>)}</div></Container></section>; }

export function WindowsPOS() { const steps=["Choose Elite or Pro","Review licence","Prepare Windows system","Fresh install or restore","Configure server for Pro","Connect Pro clients","Complete setup","Start billing"]; return <><SEO title="TurboCart Elite & Pro Windows Billing Software" description="Choose TurboCart Elite for standalone Windows billing or Pro for a server and client, multi-counter Windows setup with inventory and backups." path="/windows-pos"/><PageHero badge="TurboCart Elite & Pro" title={<>Windows billing software for <span className="text-gradient">one counter or many.</span></>} description="Choose Elite for a standalone Windows billing system or Pro for a Windows server and client setup connecting multiple billing counters."><Button to="/request-demo">Compare Elite and Pro</Button><Button to="/contact" variant="secondary">Talk to sales</Button></PageHero><WindowsEditions/><section className="pb-24"><Container><Reveal><ProductGallery/></Reveal></Container></section><section className="border-y border-white/[.07] bg-night py-24"><Container><Reveal><SectionHeading eyebrow="Fast checkout" title="A purpose-built billing workspace." description="TurboCart Windows is optimized for barcode scanning, keyboard shortcuts, customer entry, payment selection and GST calculation."/></Reveal><Reveal className="mt-12"><POSBillingDemo/></Reveal></Container></section><DetailGrid type="windows"/><section className="py-24 lg:py-32"><Container><Reveal><SectionHeading eyebrow="TurboCart Pro architecture" title="Multi-counter billing. One local network." description="A main Windows server coordinates the business database while connected Pro client systems support billing across multiple counters."/></Reveal><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1,2,3,4].map(x=><Reveal key={x} className="rounded-2xl border border-white/10 bg-white/[.03] p-6 text-center"><Monitor className="mx-auto h-8 w-8 text-cyan-300"/><p className="mt-4 font-bold">Pro client {x}</p><p className="mt-1 text-xs text-emerald-300">LAN connected</p></Reveal>)}</div></Container></section><section className="bg-night py-24 lg:py-32"><Container><Reveal><SectionHeading center eyebrow="Installation" title="Professional installation from day one." description="A clear setup workflow supports Elite, Pro, fresh installation and restoration from an existing TurboCart database."/></Reveal><div className="mt-14 grid gap-3 md:grid-cols-4">{steps.map((s,i)=><Reveal key={s} delay={(i%4)*.04} className="rounded-2xl border border-white/10 p-5"><span className="text-xs font-extrabold text-cyan-300">{String(i+1).padStart(2,"0")}</span><p className="mt-4 text-sm font-bold">{s}</p></Reveal>)}</div></Container></section><WindowsFAQ/><ProductCTA product="TurboCart Elite or Pro"/></>; }

export function CloudPage() { return <><SEO title="TurboCart Platinum Cloud SaaS | Multi-Branch ERP" description="TurboCart Platinum provides 99.99% uptime, multi-branch SaaS, Android, Windows, Linux and macOS access, dedicated backups and an own mobile e-commerce app." path="/cloud"/><PageHero badge="TurboCart Platinum" title={<>Every branch. Every platform. <span className="text-gradient">One cloud.</span></>} description="A multi-branch SaaS with 99.99% uptime, cross-platform access, dedicated backups and your own mobile e-commerce app."><Button to="/request-demo">Request a Platinum demo</Button></PageHero><PlatinumOverview/><section className="pb-24"><Container><Reveal><HeroDashboard/></Reveal></Container></section><DetailGrid type="cloud"/><section className="py-24 lg:py-32"><Container><div className="grid items-center gap-14 lg:grid-cols-2"><Reveal><SectionHeading eyebrow="Multi-branch cloud SaaS" title="Control every branch through one connected system." description="Centralize products, inventory, purchases, sales and business oversight across multiple branches while authorized teams connect from Android, Windows, Linux or macOS."/></Reveal><Reveal><NetworkDiagram/></Reveal></div></Container></section><ProductCTA product="TurboCart Platinum"/></>; }

export function MobilePage() { return <><SEO title="Mobile E-commerce App with TurboCart Platinum" description="TurboCart Platinum includes your own mobile e-commerce app connected with the cloud product catalogue, inventory and order workflow." path="/mobile"/><PageHero badge="Platinum e-commerce app" title={<>Your business. Your own <span className="text-gradient">mobile commerce app.</span></>} description="TurboCart Platinum provides a customer-facing mobile e-commerce app connected with your cloud product, inventory and order ecosystem."><Button to="/request-demo">See Platinum in action</Button></PageHero><section className="pb-24"><Container><Reveal><MobileMockup/></Reveal></Container></section><DetailGrid type="mobile"/><ProductCTA product="the Platinum e-commerce app"/></>; }
