import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { BarChart3, Bell, Boxes, CheckCircle2, Cloud, Package, ReceiptText, Search, ShoppingCart, TrendingUp, Wifi } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from "recharts";

const sales = [{ d: "Mon", v: 38 }, { d: "Tue", v: 52 }, { d: "Wed", v: 43 }, { d: "Thu", v: 70 }, { d: "Fri", v: 64 }, { d: "Sat", v: 89 }, { d: "Sun", v: 78 }];

function WindowBar({ label }: { label: string }) { return <div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div className="flex gap-1.5"><i className="h-2.5 w-2.5 rounded-full bg-rose-400/70" /><i className="h-2.5 w-2.5 rounded-full bg-amber-300/70" /><i className="h-2.5 w-2.5 rounded-full bg-emerald-400/70" /></div><span className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">{label}</span><div className="h-2 w-8 rounded-full bg-white/10" /></div>; }

export function HeroDashboard() {
  return <motion.div initial={{ opacity: 0, scale: .96, y: 30 }} animate={{ opacity: 1, scale: 1, y: 0 }} transition={{ duration: .9, delay: .25 }} className="relative mx-auto max-w-5xl rounded-[26px] border border-white/15 bg-[#070b17]/90 p-2 shadow-[0_40px_120px_rgba(0,0,0,.6),0_0_80px_rgba(37,99,235,.14)] backdrop-blur-xl">
    <WindowBar label="TurboCart · Demo dashboard" />
    <div className="grid min-h-[430px] grid-cols-[62px_1fr] overflow-hidden rounded-b-[20px] sm:grid-cols-[180px_1fr]">
      <aside className="border-r border-white/10 bg-white/[.015] p-3"><div className="mb-8 hidden items-center gap-2 px-2 text-sm font-extrabold sm:flex"><span className="grid h-7 w-7 place-items-center rounded-lg bg-blue-500 text-xs">T</span>TurboCart</div><div className="space-y-2">{[[BarChart3,"Overview"],[ReceiptText,"Billing"],[Boxes,"Inventory"],[Package,"Purchases"]].map(([Icon,label],i)=><div key={String(label)} className={`flex items-center gap-2.5 rounded-lg px-2.5 py-2.5 text-xs ${i === 0 ? "bg-blue-500/15 text-cyan-200" : "text-slate-500"}`}><Icon className="h-4 w-4" /><span className="hidden sm:inline">{String(label)}</span></div>)}</div></aside>
      <div className="min-w-0 p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] uppercase tracking-widest text-cyan-300">Demo data</p><h3 className="mt-1 text-lg font-bold">Retail overview</h3></div><span className="flex items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/5 px-3 py-1 text-[10px] text-emerald-300"><i className="h-1.5 w-1.5 animate-pulse rounded-full bg-emerald-300" /> Terminals online</span></div>
      <div className="mt-4 grid grid-cols-2 gap-2.5 lg:grid-cols-4">{[["Today’s sales","₹84,260","+8.2%"],["Transactions","326","Live"],["Products","4,826","Catalog"],["Low stock","21","Review"]].map(([a,b,c],i)=><motion.div key={a} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:.5+i*.08}} className="rounded-xl border border-white/10 bg-white/[.035] p-3"><p className="text-[10px] text-slate-500">{a}</p><p className="mt-1.5 text-lg font-bold text-white">{b}</p><p className={`mt-1 text-[9px] ${i===0?"text-emerald-300":"text-slate-500"}`}>{c}</p></motion.div>)}</div>
      <div className="mt-2.5 grid gap-2.5 lg:grid-cols-[1.6fr_1fr]"><div className="h-48 rounded-xl border border-white/10 bg-white/[.025] p-3"><div className="mb-2 flex justify-between"><p className="text-xs font-semibold">Sales trend</p><TrendingUp className="h-4 w-4 text-cyan-300" /></div><ResponsiveContainer width="100%" height="82%"><AreaChart data={sales}><defs><linearGradient id="salesFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#22d3ee" stopOpacity={.35}/><stop offset="1" stopColor="#22d3ee" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(148,163,184,.08)" vertical={false}/><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fontSize:9,fill:"#64748b"}}/><Tooltip contentStyle={{background:"#0b1020",border:"1px solid #1e293b",fontSize:10}}/><Area type="monotone" dataKey="v" stroke="#22d3ee" fill="url(#salesFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div>
      <div className="rounded-xl border border-white/10 bg-white/[.025] p-3"><p className="text-xs font-semibold">Stock attention</p><div className="mt-3 space-y-3">{[["Premium Rice","08","amber"],["Sunflower Oil","12","cyan"],["Household Cleaner","06","rose"]].map(([n,q,c])=><div key={n}><div className="flex justify-between text-[10px]"><span className="text-slate-400">{n}</span><span>{q} left</span></div><div className="mt-1.5 h-1 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${c==="amber"?"bg-amber-300":c==="cyan"?"bg-cyan-300":"bg-rose-400"}`} style={{width:`${Number(q)*4}%`}} /></div></div>)}</div></div></div></div>
    </div><div className="pointer-events-none absolute -right-5 top-24 hidden rounded-xl border border-cyan-300/20 bg-[#0b1020]/90 p-3 shadow-glow backdrop-blur md:block"><p className="text-[9px] uppercase tracking-widest text-slate-500">Terminal 02</p><p className="mt-1 flex items-center gap-2 text-xs font-bold"><Wifi className="h-3 w-3 text-emerald-300" /> Ready for billing</p></div>
  </motion.div>;
}

export function POSBillingDemo() {
  const [items, setItems] = useState(2);
  const rows = [["Aashirvaad Atta 5kg", "1", "₹318.00"], ["Fresh Milk 1L", "2", "₹120.00"], ["Sunflower Oil 1L", "1", "₹164.00"]];
  return <div className="overflow-hidden rounded-3xl border border-white/10 bg-[#080c18] shadow-2xl"><WindowBar label="TurboCart POS · UI demonstration" /><div className="grid lg:grid-cols-[1fr_290px]"><div className="p-4 sm:p-6"><div className="flex gap-2"><div className="flex flex-1 items-center gap-2 rounded-xl border border-white/10 bg-white/[.035] px-4 text-sm text-slate-500"><Search className="h-4 w-4" /> Scan barcode or search product</div><button onClick={() => setItems(3)} className="rounded-xl bg-blue-500 px-4 py-3 text-sm font-bold text-white">Add item</button></div><div className="mt-5 overflow-hidden rounded-xl border border-white/10"><div className="grid grid-cols-[1fr_36px_70px_72px] bg-white/[.04] px-3 py-2 text-[9px] uppercase tracking-widest text-slate-500"><span>Product</span><span>Qty</span><span className="text-right">Unit price</span><span className="text-right">Amount</span></div><AnimatePresence>{rows.slice(0,items).map((r,i)=><motion.div key={r[0]} initial={i===2?{opacity:0,y:-8}:{}} animate={{opacity:1,y:0}} className="grid grid-cols-[1fr_36px_70px_72px] border-t border-white/[.07] px-3 py-3 text-[11px]"><span className="truncate text-slate-300">{r[0]}</span><span>{r[1]}</span><span className="text-right text-slate-500">{i===1?"₹60.00":r[2]}</span><span className="text-right font-semibold">{r[2]}</span></motion.div>)}</AnimatePresence></div></div><aside className="border-t border-white/10 bg-blue-500/[.055] p-6 lg:border-l lg:border-t-0"><p className="text-xs font-bold uppercase tracking-widest text-cyan-300">Current bill</p><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between text-slate-400"><span>Subtotal</span><span>{items===3?"₹602.00":"₹438.00"}</span></div><div className="flex justify-between text-slate-400"><span>GST included</span><span>₹28.67</span></div><div className="flex justify-between text-slate-400"><span>Discount</span><span>− ₹12.00</span></div></div><div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs text-slate-500">Total payable</p><p className="mt-1 text-3xl font-extrabold">{items===3?"₹590.00":"₹426.00"}</p></div><label className="mt-5 block text-[10px] font-bold uppercase tracking-widest text-slate-500">Payment method<select aria-label="Payment method demonstration" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-[#0b1020] px-3 text-xs normal-case tracking-normal text-white"><option>Cash</option><option>Card</option><option>UPI</option></select></label><button className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-white py-3 text-sm font-extrabold text-slate-950"><ReceiptText className="h-4 w-4" /> Generate invoice</button><p className="mt-3 text-center text-[9px] text-slate-600">Interface demonstration only</p></aside></div></div>;
}

export function ReportsDashboard() {
  const data = [{ d: "W1", sales: 42, purchases: 30 }, { d: "W2", sales: 58, purchases: 36 }, { d: "W3", sales: 51, purchases: 28 }, { d: "W4", sales: 76, purchases: 44 }];
  return <div className="overflow-hidden rounded-3xl border border-white/10 bg-[#080c18] shadow-2xl"><WindowBar label="TurboCart Reports · Demo data"/><div className="grid gap-3 p-5 sm:grid-cols-3 sm:p-7">{[["Today’s sales","₹84,260"],["Monthly sales","₹5.42L"],["Daily closing","Ready to review"]].map(([label,value])=><div key={label} className="rounded-xl border border-white/10 bg-white/[.035] p-4"><p className="text-[10px] uppercase tracking-widest text-slate-500">{label}</p><p className="mt-2 text-xl font-extrabold">{value}</p></div>)}</div><div className="grid gap-4 px-5 pb-5 sm:px-7 sm:pb-7 lg:grid-cols-[1.5fr_1fr]"><div className="h-64 rounded-2xl border border-white/10 bg-white/[.025] p-4"><p className="text-sm font-bold">Sales and purchase overview</p><ResponsiveContainer width="100%" height="85%"><BarChart data={data}><CartesianGrid stroke="rgba(148,163,184,.08)" vertical={false}/><XAxis dataKey="d" axisLine={false} tickLine={false} tick={{fontSize:10,fill:"#64748b"}}/><Tooltip contentStyle={{background:"#0b1020",border:"1px solid #1e293b",fontSize:11}}/><Bar dataKey="sales" fill="#22d3ee" radius={[4,4,0,0]}/><Bar dataKey="purchases" fill="#6366f1" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><div className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><p className="text-sm font-bold">Top products</p><div className="mt-5 space-y-4">{[["Premium Rice","82%"],["Sunflower Oil","68%"],["Fresh Milk","55%"]].map(([name,width],i)=><div key={name}><div className="flex justify-between text-xs"><span className="text-slate-400">{name}</span><span>0{i+1}</span></div><div className="mt-2 h-1.5 rounded-full bg-white/10"><motion.div initial={{width:0}} whileInView={{width}} viewport={{once:true}} className="h-full rounded-full bg-gradient-to-r from-blue-500 to-cyan-300"/></div></div>)}</div><div className="mt-6 rounded-xl bg-blue-500/[.08] p-3 text-xs text-slate-400">Inventory summary: <b className="text-white">21 low-stock items</b></div></div></div></div>;
}

const phoneTabs = { Overview: ["Today’s sales", "₹84,260", "326 bills"], Sales: ["Sales trend", "₹5.42L", "This month"], Inventory: ["Stock health", "21 items", "Need attention"], Reports: ["Daily closing", "Ready", "Review summary"] } as const;
export function MobileMockup() {
  const [tab, setTab] = useState<keyof typeof phoneTabs>("Overview");
  const data = phoneTabs[tab];
  return <div className="flex flex-col items-center gap-8 lg:flex-row lg:justify-center"><div className="relative w-[280px] rounded-[46px] border-[7px] border-slate-700 bg-[#070b17] p-3 shadow-[0_35px_100px_rgba(37,99,235,.28)]"><div className="mx-auto mb-3 h-5 w-24 rounded-full bg-slate-800" /><div className="min-h-[480px] rounded-[32px] bg-gradient-to-b from-blue-600/20 to-transparent p-5"><div className="flex items-center justify-between"><div><p className="text-[10px] text-slate-400">Good morning</p><p className="text-sm font-bold">Retail overview</p></div><Bell className="h-5 w-5 text-slate-400" /></div><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,x:12}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-12}} transition={{duration:.22}} className="mt-8"><p className="text-xs text-cyan-300">{data[0]}</p><p className="mt-2 text-3xl font-extrabold">{data[1]}</p><p className="mt-1 text-xs text-slate-500">{data[2]} · Demo data</p><div className="mt-7 h-36 rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="flex h-full items-end gap-2">{[35,55,42,72,61,88,75].map((h,i)=><motion.div initial={{height:0}} animate={{height:`${h}%`}} transition={{delay:i*.04}} key={i} className="flex-1 rounded-t bg-gradient-to-t from-blue-600 to-cyan-300" />)}</div></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/[.05] p-3"><Boxes className="h-4 w-4 text-cyan-300"/><p className="mt-4 text-[10px] text-slate-500">Products</p><p className="text-sm font-bold">4,826</p></div><div className="rounded-xl bg-white/[.05] p-3"><CheckCircle2 className="h-4 w-4 text-emerald-300"/><p className="mt-4 text-[10px] text-slate-500">Stores</p><p className="text-sm font-bold">All synced</p></div></div></motion.div></AnimatePresence></div></div><div className="flex max-w-sm flex-wrap justify-center gap-2">{Object.keys(phoneTabs).map(t=><button key={t} onClick={()=>setTab(t as keyof typeof phoneTabs)} className={`rounded-full px-4 py-2 text-sm font-bold transition ${tab===t?"bg-white text-slate-950":"border border-white/10 text-slate-400 hover:text-white"}`}>{t}</button>)}</div></div>;
}

export function InvoiceMockup() { return <div className="mx-auto max-w-md rotate-1 rounded-sm bg-slate-100 p-7 text-slate-900 shadow-2xl sm:p-10"><div className="flex justify-between border-b border-slate-300 pb-5"><div><p className="text-xl font-extrabold">TurboCart</p><p className="text-[9px] text-slate-500">SAMPLE RETAIL INVOICE</p></div><ReceiptText className="h-7 w-7 text-blue-600" /></div><div className="mt-5 flex justify-between text-[9px] text-slate-500"><span>Invoice #TC-02481<br/>12 Aug 2026 · 11:42 AM</span><span className="text-right">GST-ready format<br/>A4 print preview</span></div><div className="mt-6 border-y border-slate-300 py-3 text-[10px]">{[["Premium Rice 5kg","₹520.00"],["Sunflower Oil 1L","₹164.00"],["Household Care","₹240.00"]].map(r=><div key={r[0]} className="flex justify-between py-1.5"><span>{r[0]}</span><b>{r[1]}</b></div>)}</div><div className="ml-auto mt-5 w-44 space-y-2 text-[10px]"><div className="flex justify-between"><span>Taxable amount</span><span>₹844.00</span></div><div className="flex justify-between"><span>GST</span><span>₹80.00</span></div><div className="flex justify-between border-t border-slate-300 pt-2 text-sm font-extrabold"><span>Total</span><span>₹924.00</span></div></div><p className="mt-8 text-center text-[8px] text-slate-400">Product UI demonstration · Not an actual invoice</p></div>; }

export function NetworkDiagram() { return <div className="relative mx-auto flex max-w-2xl flex-col items-center"><div className="rounded-2xl border border-blue-400/30 bg-blue-500/10 p-5 text-center shadow-glow"><Cloud className="mx-auto h-7 w-7 text-cyan-300"/><p className="mt-2 text-sm font-bold">TurboCart Cloud</p></div><div className="h-14 w-px bg-gradient-to-b from-cyan-300 to-blue-500"/><div className="grid w-full grid-cols-3 gap-3">{[[StoreIcon,"Store 1"],[BarChart3,"Head office"],[SmartphoneIcon,"Mobile"]].map(([Icon,label])=><div key={String(label)} className="relative rounded-2xl border border-white/10 bg-white/[.035] p-5 text-center"><span className="absolute left-1/2 top-[-58px] h-14 w-px bg-blue-500/50"/><Icon className="mx-auto h-6 w-6 text-slate-300"/><p className="mt-2 text-xs font-bold">{String(label)}</p></div>)}</div></div>; }
function StoreIcon({className}:{className?:string}) { return <ShoppingCart className={className}/>; }
function SmartphoneIcon({className}:{className?:string}) { return <Bell className={className}/>; }
